env:
  browser: true
  commonjs: true
  es6: true
extends: 'eslint:recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
rules: {
  "no-undef": "warn"
  "semi": ["warn", "always"]
  "no-extra-semi": "warn"
  "quotes": ["warn", "single"]
}
