AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Globals:
  Function:
    Runtime: nodejs10.x
    Handler: index.handler
    Timeout: 3
    MemorySize: 128
    Description: 'Created by SAM template'
Resources:
  registerObject:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: registerObject
      Role: 'arn:aws:iam::907616993345:role/Lamda'
  getSpots:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: getSpots
      Role: 'arn:aws:iam::907616993345:role/Lamda'
