version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.19
  node: circleci/node@1.1.6
  aws-serverless: circleci/aws-serverless@1.0.2

jobs:
  unit-test:
    executor: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
      - run: yarn test
  build:
    docker:
      - image: cleartone1216/aws-sam-cli:0.0.1
    steps:
      - run: sam --version
  build-test:
    executor: aws-serverless/default
    steps:
      - checkout
      - run: sudo chmod -R 775 /home/circleci/.cache
      - restore_cache:
          key: home_brew
      - aws-serverless/install
      - save_cache:
          key: home_brew
          paths: /home/circleci/.cache
      - run: sam validate
      - run: sam build
      - run: sam deploy
workflows:
  version: 2
  test-and-deploy:
    jobs:
      - unit-test
      - build
      # - build-test:
      #     requires:
      #       - unit-test
