version: 2.1
orbs:
  node: circleci/node@1.1.6

jobs:
  unit-test:
    executor: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
      - run: npm test
  build-test:
    docker:
      - image: cleartone1216/aws-sam-cli:0.0.1
    steps:
      - checkout
      - run: sam validate
      - run: sam build
      - run: sam deploy
workflows:
  version: 2
  test-and-deploy:
    jobs:
      - unit-test
      - build-test:
          requires:
            - unit-test
