version: 2.1
orbs:
  node: circleci/node@1.1.6
  aws-cli: circleci/aws-cli@0.1.13
  aws-serverless: circleci/aws-serverless@1.0.2
jobs:
  aws-cli:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: default
      - run: aws --version
  unit_test:
    executor: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
      - run: yarn test
  build_app:
    executor: aws-serverless/default
    steps:
      - checkout
      - aws-serverless/install
      - run: sam build
workflows:
  my-workflow:
    jobs:
      - aws-cli:
        context: aws
      - unit_test
      - build_app