version: 2.1
orbs:
  aws-cli: circleci/aws-cli@0.1.19
  node: circleci/node@1.1.6
  aws-serverless: circleci/aws-serverless@1.0.2

jobs:
  aws-cli-setup:
    executor: aws-cli/default
    steps:
      - aws-cli/setup:
          profile-name: default
      - run: echo "Run your code here"
  unit-test:
    executor: node/default
    steps:
      - checkout
      - run: echo "Run your code here"
workflows:
  version: 2
  test-and-deploy:
    jobs:
      - aws-cli-setup
      - unit-test

# orbs:
#   aws-cli: circleci/aws-cli@0.1.13
#   # node: circleci/node@1.1.6
#   # aws-serverless: circleci/aws-serverless@1.0.2
# jobs:
#   aws-configure:
#     executor: aws-cli/default
#     steps:
#       - checkout
#       - aws-cli/setup:
#           profile-name: default
#       - run: aws --version
#   unit_test:
#     executor: node/default
#     steps:
#       - checkout
#       - node/with-cache:
#           steps:
#             - run: yarn install
#       - run: yarn test
#   build_app:
#     executor: aws-serverless/default
#     steps:
#       - checkout
#       - aws-serverless/install
#       - run: sam build
# workflows:
#   version: 2
#   my-workflow:
#     jobs:
#       - aws-configure
#       # - unit_test
#       # - build_app