version: 2.1
orbs:
  aws-serverless: circleci/aws-serverless@1.0.2
jobs:
  test_my_api:
    executor: aws-servlerless/default
    steps:
      - run: echo "Run your tests here"
workflows:
  build_test_and_deploy:
    jobs:
      - test_my_api