version: 2.1
orbs:
  node: circleci/node@1.1.6

jobs:
  unit-test:
    executor: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
      - run: npm test
      - store_test_results:
          path: coverage
  build-test:
    docker:
      - image: cleartone1216/aws-sam-cli:0.0.2
    steps:
      - checkout
      - run: sam validate
      - run: sam build
      - run: sam deploy
  post-output:
    docker:
      - image: cleartone1216/aws-sam-cli:0.0.2
    steps:
      - run: export ApiKeyID=`aws cloudformation describe-stacks --stack-name KameraLambda | jq -r '.Stacks[].Outputs | map(select(.OutputKey == "ApiKeyID")) | .[].OutputValue'`
      - run: export ApiGatewayEndpoint=`aws cloudformation describe-stacks --stack-name KameraLambda | jq -r '.Stacks[].Outputs | map(select(.OutputKey == "ApiGatewayEndpoint")) | .[].OutputValue'`
      - run: echo $ApiKeyID
      - run: export ApiKey=`aws apigateway get-api-key --api-key $ApiKeyID --include-value | jq -r .value`
workflows:
  version: 2
  test-and-deploy:
    jobs:
      # - unit-test
      # - build-test:
      #     requires:
      #       - unit-test
      - post-output
          # requires:
          #   - build-test